// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK-UJu80-3l6axKdM_07Frj-tWxQtLACA',
    appId: '1:954938723219:web:e67df5b32e2300f22af666',
    messagingSenderId: '954938723219',
    projectId: 'farm-land-ba606',
    authDomain: 'farm-land-ba606.firebaseapp.com',
    databaseURL: 'https://farm-land-ba606-default-rtdb.firebaseio.com',
    storageBucket: 'farm-land-ba606.appspot.com',
    measurementId: 'G-LWJT6J05WJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiAY46VaZPfW3Jxse26_mSLj9EpKKdBZM',
    appId: '1:954938723219:android:d4a6fdd29fb14d8b2af666',
    messagingSenderId: '954938723219',
    projectId: 'farm-land-ba606',
    databaseURL: 'https://farm-land-ba606-default-rtdb.firebaseio.com',
    storageBucket: 'farm-land-ba606.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApo1uewgGuDTnAVKi7luNLAQUbGYKqxtI',
    appId: '1:954938723219:ios:5412514a777dedf72af666',
    messagingSenderId: '954938723219',
    projectId: 'farm-land-ba606',
    databaseURL: 'https://farm-land-ba606-default-rtdb.firebaseio.com',
    storageBucket: 'farm-land-ba606.appspot.com',
    iosBundleId: 'com.example.farmLand',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApo1uewgGuDTnAVKi7luNLAQUbGYKqxtI',
    appId: '1:954938723219:ios:45cdaf7848e837c32af666',
    messagingSenderId: '954938723219',
    projectId: 'farm-land-ba606',
    databaseURL: 'https://farm-land-ba606-default-rtdb.firebaseio.com',
    storageBucket: 'farm-land-ba606.appspot.com',
    iosBundleId: 'com.example.farmLand.RunnerTests',
  );
}
